# Generated by Django 5.2.5 on 2025-08-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('phone', models.CharField(default='', max_length=20, verbose_name='Telefone')),
                ('position', models.CharField(default='', max_length=100, verbose_name='Cargo')),
                ('company_name', models.CharField(default='', max_length=150, verbose_name='Nome da empresa')),
                ('segment', models.CharField(blank=True, choices=[('tech', 'Tecnologia'), ('fin', 'Financeiro'), ('edu', 'Educação'), ('ind', 'Indústria'), ('outros', 'Outros')], max_length=20, verbose_name='Segmento')),
                ('company_size', models.CharField(blank=True, choices=[('1-10', '1–10'), ('11-50', '11–50'), ('51-200', '51–200'), ('201-500', '201–500'), ('500+', '500+')], max_length=10, verbose_name='Tamanho da empresa')),
                ('main_interest', models.CharField(blank=True, choices=[('site', 'Site institucional'), ('app', 'Aplicativo'), ('ecom', 'E-commerce'), ('integr', 'Integrações/Automação'), ('consult', 'Consultoria'), ('outros', 'Outros')], max_length=12, verbose_name='Principal interesse')),
                ('follow_up', models.CharField(blank=True, max_length=200, verbose_name='Como soube/Follow-up')),
                ('observations', models.TextField(blank=True, verbose_name='Observações')),
                ('status', models.CharField(blank=True, choices=[('ativo', 'Ativo'), ('contratado', 'Contratado'), ('qualificado', 'Qualificado'), ('desqualificado', 'Desqualificado')], verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
