# Generated by Django 5.2.5 on 2025-08-17 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='company_name',
            field=models.CharField(default='', max_length=150, verbose_name='Nome da empresa'),
        ),
        migrations.AddField(
            model_name='lead',
            name='company_size',
            field=models.CharField(blank=True, choices=[('1-10', '1–10'), ('11-50', '11–50'), ('51-200', '51–200'), ('201-500', '201–500'), ('500+', '500+')], max_length=10, verbose_name='Tamanho da empresa'),
        ),
        migrations.AddField(
            model_name='lead',
            name='follow_up',
            field=models.CharField(blank=True, max_length=200, verbose_name='Como soube/Follow-up'),
        ),
        migrations.AddField(
            model_name='lead',
            name='main_interest',
            field=models.CharField(blank=True, choices=[('site', 'Site institucional'), ('app', 'Aplicativo'), ('ecom', 'E-commerce'), ('integr', 'Integrações/Automação'), ('consult', 'Consultoria'), ('outros', 'Outros')], max_length=12, verbose_name='Principal interesse'),
        ),
        migrations.AddField(
            model_name='lead',
            name='observations',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='lead',
            name='phone',
            field=models.CharField(default='', max_length=20, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='lead',
            name='position',
            field=models.CharField(default='', max_length=100, verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='lead',
            name='segment',
            field=models.CharField(blank=True, choices=[('tech', 'Tecnologia'), ('fin', 'Financeiro'), ('edu', 'Educação'), ('ind', 'Indústria'), ('outros', 'Outros')], max_length=20, verbose_name='Segmento'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
    ]
