# Generated by Django 5.2.5 on 2025-08-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(blank=True, choices=[('ativo', 'Ativo'), ('contratado', 'Contratado'), ('qualificado', 'Qualificado'), ('desqualificado', 'Desqualificado'), ('nao_avaliado', 'Não Avaliado')], default='nao_avaliado', max_length=20, verbose_name='Status'),
        ),
    ]
